        <h1>Task add</h1>

        <div class="col-md-8 order-md-1">
          <h1 class="mb-3"></h1>
          <form action="<?php echo $this->basePath; ?>task/add" method="POST">
            <div class="mb-3">
              <label for="username">Username</label>
              <div class="input-group">
                <input type="text" class="form-control" id="username" name="username" placeholder="Username" required>
                <div class="invalid-feedback" style="width: 100%;">Your username is required.</div>
              </div>
            </div>

            <div class="mb-3">
              <label for="email">Email <span class="text-muted"></span></label>
              <input type="email" class="form-control" id="email" name="email" placeholder="you@example.com" required>
              <div class="invalid-feedback">Please enter a valid email address.</div>
            </div>

            <div class="mb-3">
              <label for="comments">Comments</label>
              <textarea class="form-control" id="comments" name="comments"></textarea>
              <div class="invalid-feedback">Please enter task comment.</div>
            </div>



            <button class="btn btn-primary" type="submit" name="submit_add_task" value="Submit" >Add Task</button>
          </form>
        </div>

