        <h1>Task list</h1>

        <div class="mb-3"></div>
        <table id="task_list" class="table table-hover">
          <thead>
            <tr>
              <th scope="col">Id</th>
              <th scope="col">User Name</th>
              <th scope="col">Email</th>
              <th scope="col">Comments</th>


<?php if (isset($this->isAdmin) && $this->isAdmin) { ?>
              <th scope="col">Action</th>
<?php } else { ?>
              <th></th>
<?php } ?>
            </tr>
          </thead>
          <tbody>
<?php foreach ($tasks as $task) { ?>
            <tr>
              <th scope="row"><?php echo $task->id ?? $task->id; ?></th>
              <td><?php echo $task->username ?? ''; ?></td>
              <td><?php echo $task->email ?? ''; ?></td>
              <td><?php echo $task->comments ?? ''; ?></td>

<?php if (isset($this->isAdmin) && $this->isAdmin) { ?>
              <td><a href="<?php echo $this->basePath; ?>task/edit/<?php echo $task->id; ?>">Edit</a></td>
<?php } else { ?>
              <td></td>
<?php } ?>
            </tr>
<?php } ?>
          </tbody>
        </table>
        <div class="mb-3"></div>
